### PR TITLE
Split libwololokingdoms library and add Linux support

### LINKED ISSUE #8: Build details?
Hey!
I tried to build this project on Win7.
Unfortunately, I am stuck with iconv.
Although one can use genieutils.dll from the release and genieutils.dll.a from the source, one needs iconv.h for /include/genie/lang/LangFile.h.
Without it I get "undefined reference" errors in QT Creator:

> undefined reference to `genie::LangFile::setString(unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'

It would be really nice if you could provide information on the version of inconv and/or upload the bin, include and lib folders of the version used for your genieutils to some filehoster.
Thank you!

### LINKED ISSUE #13: Feature request: Split a portable library off from the main code base
If a portable library was separate from the OS dependent code (windows.h) it could be used to write cli-tools for mac and linux that can be used to get the job done without the risk of the UI not running in wine.

### PR DESCRIPTION
**Pull request by goto-bus-stop**
Hi! I'm working on an app where I'd like to programmatically invoke WololoKingdoms. This PR splits WK into an installer part and a library part, so the library can be used in other programs as well to convert an HD Edition installation to WololoKingdoms.

This adds Linux support which is no small maintenance burden—I don't expect the WK team to maintain Linux support, if it accidentally breaks I can send PRs to fix it again.

This is marked [WIP] because some changes are still untested and the build most likely doesn't work in Windows in its current state.

Changes shortlist:

- Split wkconverter.cpp to a libwololokingdoms library, pushing UI interaction over a WKConvertListener class instead of Qt signals
- Use CMake for libwololokingdoms; it's already needed for genieutils and makes sure that no Qt stuff is accidentally used in the library code
- Extract a `installUserPatch` callback function that needs to be implemented by users of the libwololokingdoms library
- Switch to C++17 so the standard C++ filesystem library can be used instead of boost
- Copy-paste some base64/md5 implementations from StackOverflow to avoid the QCryptographicHash dependency in libwololokingdoms
- Update genieutils to a modern fork, which removes boost
- Keep dependencies as git submodules so you can pull them in automatically instead of building dlls separately
- Use fs::path and the `/` operator for all filesystem operations, which works cross-platform unlike \\
- Manually write out the zip headers for ZR@ maps to avoid the QuaZip dependency in libwololokingdoms
- On Linux, use wine + regedit to find out the AoC install path
- On Linux, use a `cfs` wrapper around the `std::filesystem` functions that make it case-insensitive
- Remove unused Steamworks SDK files, only ship the header files and the steam_api dynamic libraries
- Clang-format the entire thing

TODOs:

 - [x] Make sure it works on Windows using https://developer.microsoft.com/en-us/windows/downloads/virtual-machines
 - [x] Make sure it can be built with Qt Creator
 - [x] Test ZR@ map creation
 - [x] Fix map generation (probably a lang dll issue)
 - [x] Fix some remaining crashes on Linux eg. when copying WK3.xml
 - [x] Add error on Linux if Wine is not available
 - [x] Allow configuring debug/release builds for libwololokingdoms through QMake
 - [ ] Update with changes from `master`

This patch changes how the build process works. The new instructions are documented in the same place as the old ones: https://github.com/goto-bus-stop/WololoKingdoms/tree/libwololokingdoms#how-to-build

Closes #8, because genieutils is now built as part of this project
Closes #13

### CODE REVIEW

**Comment by goto-bus-stop** [comment]
ZR@ maps still need some work!

**Comment by goto-bus-stop** [comment]
I *THINK* this works now!

**Comment by goto-bus-stop** [comment]
Per @Jineapple's build attempts, `<filesystem>` does not appear to be supported properly by mingw on windows, so this needs to wait for that to be resolved.

**Comment by goto-bus-stop** [comment]
I miiight consider adding boost again as an in-tree dependency so we don't have to wait for mingw to be fixed…

**Comment by christianpoveda** [comment]
Hey hi! Thank you for all the effort. I'd like to know if this is still blocked and if is there any way to help to make this land sooner :)

**Comment by christianpoveda** [comment]
Hey hi! Thank you for all the effort. I'd like to know if this is still blocked and if is there any way to help to make this land sooner :)

**Comment by goto-bus-stop** [comment]
Currently this appears to work on Linux but whether it works on Windows is unclear. If you have a Windows machine you can use to try figure out how to build it, that would be helpful, I think :)

I've been trying to make it work on the Appveyor Windows CI, but not with much luck so far: https://ci.appveyor.com/project/goto-bus-stop/wololokingdoms/history (source is this branch: https://github.com/goto-bus-stop/WololoKingdoms/tree/appveyor)

**Comment by christianpoveda** [comment]
No sorry, I wanted this merged because i use linux :P I don't understand windows' ecosystem well enough to know why compilation is failing on appveyor

**Comment by goto-bus-stop** [comment]
That's fair enough :smile: 

You can pull down this branch and compile everything manually today. It works on Linux.

**Comment by goto-bus-stop** [comment]
Appveyor is looking quite promising after I switched the main build to CMake!

**Comment by goto-bus-stop** [comment]
CI is now passing on Linux and Windows :tada: 

Linux with GCC and Clang: https://travis-ci.com/goto-bus-stop/WololoKingdoms/builds/113788044

Windows with MSVC: https://ci.appveyor.com/project/goto-bus-stop/wololokingdoms/builds/24931999

**Pull request merged**
